obj-y += memory_snapshot.o
obj-y += track_syscalls.o
obj-y += io_throttle.o
obj-y += alejo_tamalloc.o
obj-y += alejo_estadisticas_ind.o
obj-y += alejo_estadisticas_tod.o
obj-y += alejo_mani_mem.o